services:
  # Redis for Bull Queue
  redis:
    image: redis:7-alpine
    container_name: renovation-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # PDF Worker Service
  pdf-worker:
    build:
      context: .
      dockerfile: pdf-worker/Dockerfile
    container_name: renovation-pdf-worker-prod
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1536
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_CONCURRENCY=2
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Monitoring (optional)
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: renovation-redis-exporter-prod
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "9121:9121"
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: renovation_network